/**
 * Average annual homeowners-insurance premium by state (USD).
 * Modeled on LendingTree / Insurance.com state averages, 2025 — refresh annually.
 * National average ≈ $2,395. Used as: monthlyInsurance = annual / 12.
 *
 * These are state averages for a typical single-family home; an individual
 * quote varies with home value, age, and coverage.
 */
export const INSURANCE_ANNUAL: Record<string, number> = {
  AL: 2200,
  AK: 1100,
  AZ: 1900,
  AR: 2900,
  CA: 1400,
  CO: 4300,
  CT: 1800,
  DE: 1000,
  DC: 1500,
  FL: 4400,
  GA: 2300,
  HI: 800,
  ID: 1300,
  IL: 2500,
  IN: 2000,
  IA: 2500,
  KS: 3800,
  KY: 2900,
  LA: 4500,
  ME: 1200,
  MD: 1600,
  MA: 1800,
  MI: 2100,
  MN: 2700,
  MS: 3500,
  MO: 3100,
  MT: 2700,
  NE: 5000,
  NV: 1300,
  NH: 1100,
  NJ: 1300,
  NM: 2400,
  NY: 1800,
  NC: 2200,
  ND: 2400,
  OH: 1500,
  OK: 5300,
  OR: 1000,
  PA: 1400,
  RI: 1800,
  SC: 2400,
  SD: 3000,
  TN: 2500,
  TX: 4200,
  UT: 1200,
  VT: 950,
  VA: 1700,
  WA: 1300,
  WV: 1700,
  WI: 1600,
  WY: 1900,
};

/** National-average fallback if a state code is missing. */
export const NATIONAL_AVG_INSURANCE = 2395;

export function insuranceAnnual(stateCode: string): number {
  return INSURANCE_ANNUAL[stateCode] ?? NATIONAL_AVG_INSURANCE;
}

/** US states + DC, for the wizard dropdown. */
export const US_STATES: { code: string; name: string }[] = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "DC", name: "District of Columbia" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
];
